
/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.springMongo;

import java.util.List;

import javax.inject.Named;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.demo.data.record.AuthorRecord;
import org.demo.persistence.AuthorPersistence;
import org.demo.persistence.impl.springMongo.commons.GenericSpringDataMongoDb;

/**
 * Author persistence service - SpringMongo implementation 
 * 
 * @author Telosys
 *
 */
@Named("AuthorPersistence")
public class AuthorPersistenceSpringMongo extends GenericSpringDataMongoDb<AuthorRecord> implements AuthorPersistence {

	/**
	 * Constructor
	 */
	public AuthorPersistenceSpringMongo() {
		super("author", AuthorRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private AuthorRecord newInstanceWithPrimaryKey(Integer id) {
		AuthorRecord record = new AuthorRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(AuthorRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	@Override
	protected Update updateQuery(AuthorRecord record) {
		Update update = new Update();
		update.set("firstName", record.getFirstName());
		update.set("lastName", record.getLastName());
		return update;
	}

	@Override
	protected Query queryForIdentifyBean(AuthorRecord record, MongoConverter converter) {
		Object keyid = converter.convertToMongoType(record.getId());
		Query query = new Query(Criteria.where("id").is(keyid));
	    return query;
	}
	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public AuthorRecord create(AuthorRecord record) {
		super.doInsert(record);
		return record;
	}

	@Override
	public boolean delete(AuthorRecord record) {
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean deleteById(Integer id) {
		AuthorRecord record = newInstanceWithPrimaryKey(id);
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean exists(AuthorRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		AuthorRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<AuthorRecord> findAll() {
		return super.doSelectAll();
	}

	@Override
	public AuthorRecord findById(Integer id) {
        AuthorRecord record = newInstanceWithPrimaryKey(id);
		return super.doSelect(record);
	}

	@Override
	public AuthorRecord save(AuthorRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doInsert(record);
		}
        return record;
	}

	@Override
	public boolean update(AuthorRecord record) {
		return super.doUpdate(record);	
	}
}
