
/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.springMongo;

import java.util.List;


import javax.inject.Named;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.demo.data.record.BadgeRecord;
import org.demo.persistence.BadgePersistence;
import org.demo.persistence.impl.springMongo.commons.GenericSpringDataMongoDb;

/**
 * Badge persistence service - SpringMongo implementation 
 * 
 * @author Telosys
 *
 */
@Named("BadgePersistence")
public class BadgePersistenceSpringMongo extends GenericSpringDataMongoDb<BadgeRecord> implements BadgePersistence {

	/**
	 * Constructor
	 */
	public BadgePersistenceSpringMongo() {
		super("badge", BadgeRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param badgeNumber
	 * @return the new instance
	 */
	private BadgeRecord newInstanceWithPrimaryKey(Integer badgeNumber) {
		BadgeRecord record = new BadgeRecord();
        record.setBadgeNumber(badgeNumber); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(BadgeRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	@Override
	protected Update updateQuery(BadgeRecord record) {
		Update update = new Update();
		update.set("authorizationLevel", record.getAuthorizationLevel());
		update.set("endOfValidity", record.getEndOfValidity());
		return update;
	}

	@Override
	protected Query queryForIdentifyBean(BadgeRecord record, MongoConverter converter) {
		Object keybadgeNumber = converter.convertToMongoType(record.getBadgeNumber());
		Query query = new Query(Criteria.where("badgeNumber").is(keybadgeNumber));
	    return query;
	}
	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public BadgeRecord create(BadgeRecord record) {
		super.doInsert(record);
		return record;
	}

	@Override
	public boolean delete(BadgeRecord record) {
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean deleteById(Integer badgeNumber) {
		BadgeRecord record = newInstanceWithPrimaryKey(badgeNumber);
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean exists(BadgeRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer badgeNumber) {
		BadgeRecord record = newInstanceWithPrimaryKey(badgeNumber);
		return super.doExists(record);
	}

	@Override
	public List<BadgeRecord> findAll() {
		return super.doSelectAll();
	}

	@Override
	public BadgeRecord findById(Integer badgeNumber) {
        BadgeRecord record = newInstanceWithPrimaryKey(badgeNumber);
		return super.doSelect(record);
	}

	@Override
	public BadgeRecord save(BadgeRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doInsert(record);
		}
        return record;
	}

	@Override
	public boolean update(BadgeRecord record) {
		return super.doUpdate(record);	
	}
}
