
/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.springMongo;

import java.util.List;


import javax.inject.Named;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.demo.data.record.BookOrderRecord;
import org.demo.persistence.BookOrderPersistence;
import org.demo.persistence.impl.springMongo.commons.GenericSpringDataMongoDb;

/**
 * BookOrder persistence service - SpringMongo implementation 
 * 
 * @author Telosys
 *
 */
@Named("BookOrderPersistence")
public class BookOrderPersistenceSpringMongo extends GenericSpringDataMongoDb<BookOrderRecord> implements BookOrderPersistence {

	/**
	 * Constructor
	 */
	public BookOrderPersistenceSpringMongo() {
		super("bookOrder", BookOrderRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private BookOrderRecord newInstanceWithPrimaryKey(Integer id) {
		BookOrderRecord record = new BookOrderRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(BookOrderRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	@Override
	protected Update updateQuery(BookOrderRecord record) {
		Update update = new Update();
		update.set("shopCode", record.getShopCode());
		update.set("customerCode", record.getCustomerCode());
		update.set("employeeCode", record.getEmployeeCode());
		update.set("date", record.getDate());
		update.set("state", record.getState());
		return update;
	}

	@Override
	protected Query queryForIdentifyBean(BookOrderRecord record, MongoConverter converter) {
		Object keyid = converter.convertToMongoType(record.getId());
		Query query = new Query(Criteria.where("id").is(keyid));
	    return query;
	}
	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public BookOrderRecord create(BookOrderRecord record) {
		super.doInsert(record);
		return record;
	}

	@Override
	public boolean delete(BookOrderRecord record) {
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean deleteById(Integer id) {
		BookOrderRecord record = newInstanceWithPrimaryKey(id);
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean exists(BookOrderRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		BookOrderRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<BookOrderRecord> findAll() {
		return super.doSelectAll();
	}

	@Override
	public BookOrderRecord findById(Integer id) {
        BookOrderRecord record = newInstanceWithPrimaryKey(id);
		return super.doSelect(record);
	}

	@Override
	public BookOrderRecord save(BookOrderRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doInsert(record);
		}
        return record;
	}

	@Override
	public boolean update(BookOrderRecord record) {
		return super.doUpdate(record);	
	}
}
