
/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.springMongo;

import java.util.List;


import javax.inject.Named;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.demo.data.record.BookOrderItemRecord;
import org.demo.persistence.BookOrderItemPersistence;
import org.demo.persistence.impl.springMongo.commons.GenericSpringDataMongoDb;

/**
 * BookOrderItem persistence service - SpringMongo implementation 
 * 
 * @author Telosys
 *
 */
@Named("BookOrderItemPersistence")
public class BookOrderItemPersistenceSpringMongo extends GenericSpringDataMongoDb<BookOrderItemRecord> implements BookOrderItemPersistence {

	/**
	 * Constructor
	 */
	public BookOrderItemPersistenceSpringMongo() {
		super("bookOrderItem", BookOrderItemRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param bookOrderId
	 * @param bookId
	 * @return the new instance
	 */
	private BookOrderItemRecord newInstanceWithPrimaryKey(Integer bookOrderId, Integer bookId) {
		BookOrderItemRecord record = new BookOrderItemRecord();
        record.setBookOrderId(bookOrderId); 
        record.setBookId(bookId); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(BookOrderItemRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	@Override
	protected Update updateQuery(BookOrderItemRecord record) {
		Update update = new Update();
		update.set("quantity", record.getQuantity());
		update.set("price", record.getPrice());
		return update;
	}

	@Override
	protected Query queryForIdentifyBean(BookOrderItemRecord record, MongoConverter converter) {
		Object keybookOrderId = converter.convertToMongoType(record.getBookOrderId());
		Object keybookId = converter.convertToMongoType(record.getBookId());
		Query query = new Query(Criteria.where("bookOrderId").is(keybookOrderId) .and("bookId").is(keybookId));
	    return query;
	}
	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public BookOrderItemRecord create(BookOrderItemRecord record) {
		super.doInsert(record);
		return record;
	}

	@Override
	public boolean delete(BookOrderItemRecord record) {
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean deleteById(Integer bookOrderId, Integer bookId) {
		BookOrderItemRecord record = newInstanceWithPrimaryKey(bookOrderId, bookId);
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean exists(BookOrderItemRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer bookOrderId, Integer bookId) {
		BookOrderItemRecord record = newInstanceWithPrimaryKey(bookOrderId, bookId);
		return super.doExists(record);
	}

	@Override
	public List<BookOrderItemRecord> findAll() {
		return super.doSelectAll();
	}

	@Override
	public BookOrderItemRecord findById(Integer bookOrderId, Integer bookId) {
        BookOrderItemRecord record = newInstanceWithPrimaryKey(bookOrderId, bookId);
		return super.doSelect(record);
	}

	@Override
	public BookOrderItemRecord save(BookOrderItemRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doInsert(record);
		}
        return record;
	}

	@Override
	public boolean update(BookOrderItemRecord record) {
		return super.doUpdate(record);	
	}
}
