
/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.springMongo;

import java.util.List;


import javax.inject.Named;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.demo.data.record.EmployeeRecord;
import org.demo.persistence.EmployeePersistence;
import org.demo.persistence.impl.springMongo.commons.GenericSpringDataMongoDb;

/**
 * Employee persistence service - SpringMongo implementation 
 * 
 * @author Telosys
 *
 */
@Named("EmployeePersistence")
public class EmployeePersistenceSpringMongo extends GenericSpringDataMongoDb<EmployeeRecord> implements EmployeePersistence {

	/**
	 * Constructor
	 */
	public EmployeePersistenceSpringMongo() {
		super("employee", EmployeeRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param code
	 * @return the new instance
	 */
	private EmployeeRecord newInstanceWithPrimaryKey(String code) {
		EmployeeRecord record = new EmployeeRecord();
        record.setCode(code); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(EmployeeRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	@Override
	protected Update updateQuery(EmployeeRecord record) {
		Update update = new Update();
		update.set("shopCode", record.getShopCode());
		update.set("firstName", record.getFirstName());
		update.set("lastName", record.getLastName());
		update.set("manager", record.getManager());
		update.set("badgeNumber", record.getBadgeNumber());
		update.set("email", record.getEmail());
		return update;
	}

	@Override
	protected Query queryForIdentifyBean(EmployeeRecord record, MongoConverter converter) {
		Object keycode = converter.convertToMongoType(record.getCode());
		Query query = new Query(Criteria.where("code").is(keycode));
	    return query;
	}
	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public EmployeeRecord create(EmployeeRecord record) {
		super.doInsert(record);
		return record;
	}

	@Override
	public boolean delete(EmployeeRecord record) {
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean deleteById(String code) {
		EmployeeRecord record = newInstanceWithPrimaryKey(code);
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean exists(EmployeeRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(String code) {
		EmployeeRecord record = newInstanceWithPrimaryKey(code);
		return super.doExists(record);
	}

	@Override
	public List<EmployeeRecord> findAll() {
		return super.doSelectAll();
	}

	@Override
	public EmployeeRecord findById(String code) {
        EmployeeRecord record = newInstanceWithPrimaryKey(code);
		return super.doSelect(record);
	}

	@Override
	public EmployeeRecord save(EmployeeRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doInsert(record);
		}
        return record;
	}

	@Override
	public boolean update(EmployeeRecord record) {
		return super.doUpdate(record);	
	}
}
