
/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.springMongo;

import java.util.List;


import javax.inject.Named;
import org.springframework.data.mongodb.core.convert.MongoConverter;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.demo.data.record.PublisherRecord;
import org.demo.persistence.PublisherPersistence;
import org.demo.persistence.impl.springMongo.commons.GenericSpringDataMongoDb;

/**
 * Publisher persistence service - SpringMongo implementation 
 * 
 * @author Telosys
 *
 */
@Named("PublisherPersistence")
public class PublisherPersistenceSpringMongo extends GenericSpringDataMongoDb<PublisherRecord> implements PublisherPersistence {

	/**
	 * Constructor
	 */
	public PublisherPersistenceSpringMongo() {
		super("publisher", PublisherRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param code
	 * @return the new instance
	 */
	private PublisherRecord newInstanceWithPrimaryKey(Integer code) {
		PublisherRecord record = new PublisherRecord();
        record.setCode(code); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected void setAutoIncrementedKey(PublisherRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	@Override
	protected Update updateQuery(PublisherRecord record) {
		Update update = new Update();
		update.set("countryCode", record.getCountryCode());
		update.set("name", record.getName());
		update.set("email", record.getEmail());
		update.set("contact", record.getContact());
		update.set("city", record.getCity());
		update.set("zipCode", record.getZipCode());
		update.set("phone", record.getPhone());
		return update;
	}

	@Override
	protected Query queryForIdentifyBean(PublisherRecord record, MongoConverter converter) {
		Object keycode = converter.convertToMongoType(record.getCode());
		Query query = new Query(Criteria.where("code").is(keycode));
	    return query;
	}
	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public PublisherRecord create(PublisherRecord record) {
		super.doInsert(record);
		return record;
	}

	@Override
	public boolean delete(PublisherRecord record) {
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean deleteById(Integer code) {
		PublisherRecord record = newInstanceWithPrimaryKey(code);
		if(super.doExists(record))
			return super.doDelete(record);
		return false;
	}

	@Override
	public boolean exists(PublisherRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer code) {
		PublisherRecord record = newInstanceWithPrimaryKey(code);
		return super.doExists(record);
	}

	@Override
	public List<PublisherRecord> findAll() {
		return super.doSelectAll();
	}

	@Override
	public PublisherRecord findById(Integer code) {
        PublisherRecord record = newInstanceWithPrimaryKey(code);
		return super.doSelect(record);
	}

	@Override
	public PublisherRecord save(PublisherRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doInsert(record);
		}
        return record;
	}

	@Override
	public boolean update(PublisherRecord record) {
		return super.doUpdate(record);	
	}
}
