/*
 * Created on 2017-03-29 ( Time 11:30:15 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.persistence.impl.springMongo.commons;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;


import org.junit.Test;
import org.springframework.data.mongodb.core.MongoTemplate;

/**
 * Spring Mongo Sequence class Integration Test <br>
 * 
 * @author Telosys 
 *
 */
public class SequenceDAOTest {

	@Test
	public void test1() throws Exception {
		System.out.println("--- test1");
        MongoTemplate mongoTemplate = SpringGetConfig.getMongotemplate();
    	SequenceDAO sequence = new SequenceDAO(mongoTemplate,"seqTest");

    	assertEquals( 0L, sequence.currVal("seqTest") );

    	assertEquals( 1L, sequence.nextVal("seqTest") );
    	System.out.println("Sequence currVal() = " + sequence.currVal("seqTest") );
    	
    	for ( int i=0 ; i < 10 ; i++ ) {
        	sequence.nextVal("seqTest") ;
    	}
    	System.out.println("Sequence currVal() = " + sequence.currVal("seqTest") );
    	assertEquals( 11L, sequence.currVal("seqTest") );

		boolean b = sequence.delete("seqTest");
        assertTrue(b);
    	System.out.println("Sequence deleted");	
	}	
}
