/*
 * Created on 2017-03-29 ( Time 11:30:15 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.persistence.impl.springMongo.commons;

import org.demo.persistence.impl.springMongo.commons.SpringGetConfig;
import org.junit.Assert;
import org.junit.Test;
import java.util.logging.*;
import org.springframework.data.mongodb.core.MongoTemplate;

/**
 * JUnit tests for SpringGetConfig
 * 
 * @author Telosys 
 *
 */
public class SpringGetConfigTest {
	private static final Logger LOGGER = Logger.getLogger(SpringGetConfigTest.class.getName());

	@Test
	public void test2MongoClient() {
    	LOGGER.info("--- test MongoTemplate ");	
    	MongoTemplate mongoTemplate = SpringGetConfig.getMongotemplate();
    	LOGGER.info("mongoTemplate ready. ");   	
    	Assert.assertNotNull( mongoTemplate );
	}
}