/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.springMongo.commons;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.FindAndModifyOptions;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;

public class SequenceDAO {

	@Autowired
	private MongoTemplate mongoTemplate;
	
	public SequenceDAO(MongoTemplate mongoTemplate, String name) {
		this.mongoTemplate = mongoTemplate;
		mongoTemplate.save(new Sequence(name,0L));
	}

	public long currVal(String key) {
		Query query = new Query(Criteria.where("id").is(key));
		Sequence seq = mongoTemplate.findOne(query, Sequence.class);
		return seq.getSeq();
	}

	public long nextVal(String key) throws Exception {
		Query query = new Query(Criteria.where("id").is(key));
		Update update = new Update();
		update.inc("seq", 1);
		FindAndModifyOptions options = new FindAndModifyOptions();
		options.returnNew(true);
		Sequence seq = mongoTemplate.findAndModify(query, update, options, Sequence.class);
		if (seq == null) {
			throw new Exception("Unable to get sequence id for key : " + key);
		}
		return seq.getSeq();
	}

	public boolean delete(String key) {
		Query query = new Query(Criteria.where("id").is(key));
		mongoTemplate.remove(query, Sequence.class);
		return true;
	}
}
