/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.springMongo.commons;

import org.springframework.data.annotation.Id;

public class Sequence {
	@Id
	private String id;
	private long seq;
	
	public Sequence(String id, long seq) {
		this.id = id;
		this.seq = seq;
	}
	
	public long getSeq() {
		return seq;
	}
	public void setSeq(long seq) {
		this.seq = seq;
	}

}
