/*
 * Created on 2017-03-29 ( Date ISO 2017-03-29 - Time 11:30:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
/*
 * Created on 2017-03-29 ( Time 11:30:14 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.persistence.impl.springMongo.commons;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.data.mongodb.core.MongoTemplate;

public class SpringGetConfig {
	private static final ApplicationContext ctx = new AnnotationConfigApplicationContext(SpringMongoConfig.class);
	private static final MongoTemplate mongoTemplate = (MongoTemplate) ctx.getBean("mongoTemplate");

	public static MongoTemplate getMongotemplate() {
		return mongoTemplate;
	}
}